- name: Copy logind.conf to remote host
  ansible.builtin.copy: 
    src: ../files/logind.conf
    dest: /etc/systemd/logind.conf
  register: logind_conf_changed

- name: Restart logind
  ansible.builtin.systemd:
    name: systemd-logind.service
    state: restarted
  when: logind_conf_changed.changed

# https://kind.sigs.k8s.io/docs/user/known-issues#pod-errors-due-to-too-many-open-files
- name: Add rules to fix kind issue with fs.inotify.max_user_watches
  copy:
    dest: "/etc/sysctl.d/98-sysctl.conf"
    src: "../files/98-sysctl.conf"
    mode: '0644'

- name: dnf install
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _dnf }}"
  register: result
  until: result is succeeded
  notify:
    - podman | system rest
    - podman | systemctl restart podman.service