- name: home server kind
  hosts: home_server
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: ../vars
        depth: 1

    - name: include role
      ansible.builtin.include_role:
        name: "../roles/kind"
        apply: 
          become: true

    - name: build main kind cluster
      include_tasks: ../tasks/create-cluster.yml
      vars:
        cluster_name: "main"
        kind_image_version: "v1.32.1"